//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdministradorModel
    {
        public int id_ad { get; set; }

        [Required(ErrorMessage = "El nombre es obligatorio.")]
        [StringLength(100, ErrorMessage = "El nombre no puede exceder los 100 caracteres.")]
        public string nombre_ad { get; set; }

         [Required(ErrorMessage = "El teléfono es obligatorio.")]
        public Nullable<int> teléfono_ad { get; set; }
        
        [Required(ErrorMessage = "La dirreción es obligatoria.")]
        [StringLength(100, ErrorMessage = "La dirreción no puede exceder los 100 caracteres.")]
        public string dirección_ad { get; set; }

        [Required(ErrorMessage = "El correo es obligatorio.")]
        [StringLength(100, ErrorMessage = "El correo no puede exceder los 100 caracteres.")]
        public string correo_ad { get; set; }

        public Nullable<int> id_usuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
