//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.Models
{
    using System;
    using System.Collections.Generic;

    public partial class EmpleadosModel
    {
        public EmpleadosModel()
        {
            this.Reservas = new HashSet<Reservas>();
        }

        public int id_empleados { get; set; }
        public string nombre_emp { get; set; }
        public Nullable<int> teléfono_emp { get; set; }
        public string dirección_emp { get; set; }
        public string correo_emp { get; set; }

        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
