//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmpleadosModel
    {
        public EmpleadosModel()
        {
            this.Reservas = new HashSet<Reservas>();
        }
        
        public int id_empleados { get; set; }

        [Required(ErrorMessage = "El nombre es obligatorio.")]
        [StringLength(100, ErrorMessage = "El nombre no puede exceder los 100 caracteres.")]
        public string nombre_emp { get; set; }

         [Required(ErrorMessage = "El teléfono es obligatorio.")]
        public Nullable<int> teléfono_emp { get; set; }

        [Required(ErrorMessage = "La dirreción es obligatoria.")]
        [StringLength(100, ErrorMessage = "La dirreción no puede exceder los 100 caracteres.")]
        public string dirección_emp { get; set; }

        [Required(ErrorMessage = "El correo es obligatorio.")]
        [StringLength(100, ErrorMessage = "El correo no puede exceder los 100 caracteres.")]
        public string correo_emp { get; set; }

        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
