//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.Models 
{
    using System;
    using System.Collections.Generic;

    public partial class ReservasModel
    {
        public ReservasModel()
        {
            this.Facturas = new HashSet<Facturas>();
            this.Reservas_servicios = new HashSet<Reservas_servicios>();
        }

        public int id_reservas { get; set; }
        public Nullable<int> id_empleados { get; set; }
        public Nullable<int> id_clientes { get; set; }
        public Nullable<int> id_metodos_pg { get; set; }
        public Nullable<System.DateTime> fecha_reserva { get; set; }

        public virtual Clientes Clientes { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual ICollection<Facturas> Facturas { get; set; }
        public virtual Metodos_Pago Metodos_Pago { get; set; }
        public virtual ICollection<Reservas_servicios> Reservas_servicios { get; set; }
    }
}
