//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UsuariosModel
    {
        public UsuariosModel()
        {
            this.Administrador = new HashSet<Administrador>();
            this.Clientes = new HashSet<Clientes>();
        }

        public int id_usuario { get; set; }

        [Required(ErrorMessage = "El usuario es obligatorio.")]
        [StringLength(100, ErrorMessage = "El usuario no puede exceder los 100 caracteres.")]
        public string usuario { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string contraseña { get; set; }

        public virtual ICollection<Administrador> Administrador { get; set; }
        public virtual ICollection<Clientes> Clientes { get; set; }
    }
}
